FROM node:22 AS build

ARG VITE_AUTH_URL
ARG VITE_CAT_DB_URL
ARG VITE_FAVORITES_SERVICE_URL
ARG VITE_PREFERENCES_DB_URL
ARG VITE_RECOMMENDER_SERVICE_URL

ENV VITE_AUTH_URL=$VITE_AUTH_URL
ENV VITE_CAT_DB_URL=$VITE_CAT_DB_URL
ENV VITE_FAVORITES_SERVICE_URL=$VITE_FAVORITES_SERVICE_URL
ENV VITE_PREFERENCES_DB_URL=$VITE_PREFERENCES_DB_URL
ENV VITE_RECOMMENDER_SERVICE_URL=$VITE_RECOMMENDER_SERVICE_URL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]